#!/usr/bin/env bash
# content-time activation runner v10 (any ranker-served feed group; R4 main feeds were the first use) -- receipted, owner-gated apply of the four-row atomic catalog
# change, modelled on the R2 Phase-3 bulk mechanism. Runs ON THE HOST as root (sudo -n bash ...) because it needs
# /etc/newsflows/secrets/feedgen.env (never printed) and the bskyops tool. Every step writes into $E (root:newsflows 0640).
#   env: E PACKET_PATH (the approved packet file) EXPECTED_PACKET_SHA (from the ledger approval) TREE_CATALOG (the DEPLOYED
#        catalog /opt/newsflows/config/newsflows/catalogs/publishers.yml) CATALOG_SOURCE_SHA (merged origin/main commit whose
#        config/newsflows/catalogs/publishers.yml must be byte-identical to TREE_CATALOG; verified against ROOT_CHECKOUT)
#        EXPECTED_UPDATE_RKEYS(csv) EXPECTED_CLOCK EXPECTED_FLOOR EXPECTED_CONTRACT (each must literally
#        appear in the approved packet) EXPECTED_TOOL_REFS (bsky-ops=<sha>,newsflows-bskyhealth=<sha>,blueskyranker=<sha>)
#        FEEDGEN_URL(http://127.0.0.1:3020) EFFECTIVE_CONFIG_JSON APPLIED_AT (battery: ISO time of the apply, from apply-transport.txt)
#   sub: preview | apply | parity | rollback-dryrun | rollback | battery <label>
set -euo pipefail
: "${E:?}"; : "${PACKET_PATH:?}"; : "${EXPECTED_PACKET_SHA:?}"; : "${TREE_CATALOG:?}"; : "${CATALOG_SOURCE_SHA:?}"; : "${EXPECTED_UPDATE_RKEYS:?}"; : "${EXPECTED_CLOCK:=content_time_v1}"; : "${EXPECTED_FLOOR:?}"; : "${EXPECTED_CONTRACT:=newsflows-content-time/v2}"; : "${EXPECTED_TOOL_REFS:?}"
# PREDECESSOR_SOURCE_SHA: the origin/main commit BEFORE the activation catalog change (its publishers.yml is the exact predecessor file;
# rollback re-projects it and parity is then evaluated against it). CONFORMANCE_BASELINE_DRIFT: the pre-existing drift items (csv).
: "${PREDECESSOR_SOURCE_SHA:?}"; CONFORMANCE_BASELINE_DRIFT="${CONFORMANCE_BASELINE_DRIFT:-health-secrets,venv-ownership}"
# v10: BSR_UNIT = the systemd unit of the ranker instance serving EXPECTED_UPDATE_RKEYS; EXPECTED_BSR_HANDLES = its publisher handles (csv)
BSR_UNIT="${BSR_UNIT:-bsr-ranker@main.service}"; EXPECTED_BSR_HANDLES="${EXPECTED_BSR_HANDLES:-news-flows-nl.bsky.social,news-flows-fr.bsky.social,news-flows-cz.bsky.social,news-flows-ir.bsky.social}"
# EXPECTED_CATALOG_SHA / EXPECTED_PREDECESSOR_CATALOG_SHA: SHA-256 of publishers.yml AFTER (activation) and BEFORE (predecessor) -- both
# named in the approved packet; EXPECTED_ROLLBACK_SHA: the rollback body hash the owner approved (apply/battery/rollback assert it)
: "${EXPECTED_CATALOG_SHA:?}"; : "${EXPECTED_PREDECESSOR_CATALOG_SHA:?}"
[[ "$CATALOG_SOURCE_SHA" =~ ^[0-9a-f]{40}$ ]] || die_early=1; [[ "$PREDECESSOR_SOURCE_SHA" =~ ^[0-9a-f]{40}$ ]] || die_early=1
# hashes of the runner's own gate tools (named in the packet), the health bot requester (sha256 of its DID), and the approval records
: "${EXPECTED_RUNNER_SHA:?}"; : "${EXPECTED_SHADOW_SQL_SHA:?}"; : "${EXPECTED_LATENCY_SH_SHA:?}"; : "${EXPECTED_REQUESTER_SHA:?}"; : "${EXPECTED_FEEDGEN_IMAGE:?EXPECTED_FEEDGEN_IMAGE (docker image ID of the running feedgen, named in the packet) is required}"; : "${EXPECTED_SCORE_BACKED_FLOOR:=0.80}"
FEEDGEN_URL="${FEEDGEN_URL:-http://127.0.0.1:3020}"; EFFECTIVE_CONFIG_JSON="${EFFECTIVE_CONFIG_JSON:-/opt/newsflows/blueskyranker_v2/logs/effective_config_readback.json}"
BSKYOPS="${BSKYOPS:-bskyops}"; ENV_FILE="${ENV_FILE:-/etc/newsflows/secrets/feedgen.env}"; ROOT_CHECKOUT="${ROOT_CHECKOUT:-/opt/newsflows/code/newsflows-bsky-ecosystem-07111009}"
HEALTH_PY="${HEALTH_PY:-/opt/newsflows/tools/uv/newsflows-bskyhealth/bin/python}"
log() { echo "[r4] $*" >&2; }; die() { echo "[r4] STOP (gate FAIL / hard stop): $*" >&2; exit 2; }; die_precondition() { echo "[r4] PRECONDITION (not a gate FAIL, not a rollback trigger): $*" >&2; if [[ -d "${E:-}" ]]; then local f="$E/PRECONDITION-$(date -u +%Y%m%dT%H%M%SZ).txt"; { echo "precondition_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)"; echo "reason=$*"; echo "subcommand=${SUBCMD_FOR_RECEIPT:-${1:-}}"; } > "$f" 2>/dev/null && chgrp newsflows "$f" 2>/dev/null && chmod 640 "$f" 2>/dev/null || true; fi; exit 4; }; ts() { date -u +%Y-%m-%dT%H:%M:%SZ; }
[[ "${die_early:-0}" == "1" ]] && die "CATALOG_SOURCE_SHA / PREDECESSOR_SOURCE_SHA must be full 40-hex commit ids (symbolic refs such as origin/main are refused)"
emit() { local n=$1; [[ -e "$E/$n" ]] && die "refusing to overwrite $E/$n"; install -o root -g newsflows -m 640 /dev/stdin "$E/$n"; log "wrote $n"; }
if [[ "${1:-}" == "apply" ]] && compgen -G "$E/rollback-rowstate-gate-*.txt" >/dev/null; then
  die_precondition "verified restore evidence already exists in $E; use a fresh evidence root and re-preview before any new apply"
fi
[[ $(id -u) -eq 0 ]] || die "run as root (sudo -n)"
[[ -d "$E" ]] || install -d -o root -g newsflows -m 750 "$E"
HDR=""; trap '[[ -n "$HDR" ]] && rm -f "$HDR"' EXIT INT TERM HUP
load_keys() {  # extract ONLY the admin key into a 0600 header file (never exported to children); removed by the EXIT trap
  HDR=$(mktemp); chmod 600 "$HDR"
  ( set -a; . "$ENV_FILE"; set +a; : "${FEEDGEN_ADMIN_API_KEY:?}"; printf 'api-key: %s\n' "$FEEDGEN_ADMIN_API_KEY" ) > "$HDR"
  # bskyops readback needs the READ key in its environment: pass it via a scrubbed sub-environment (see bskyops_env)
}
bskyops_env() { ( set -a; . "$ENV_FILE"; set +a; env -i PATH="$PATH" HOME="$HOME" FEEDGEN_READ_API_KEY="${FEEDGEN_READ_API_KEY:-}" FEEDGEN_ADMIN_API_KEY="${FEEDGEN_ADMIN_API_KEY:-}" "$@" ); }
psqlq() { docker exec -i feedgen-db psql -U feedgen -d feedgen-db -X -A -F '|' -v ON_ERROR_STOP=1 "$@"; }
tool_ref() { node -e 'const fs=require("fs");const base=process.argv[1];let out="";for(const py of fs.readdirSync(base+"/lib").filter(d=>d.startsWith("python3"))){const sp=base+"/lib/"+py+"/site-packages";for(const d of fs.readdirSync(sp).filter(d=>d.endsWith(".dist-info")&&d.toLowerCase().replace(/_/g,"-").startsWith(process.argv[2]))){const f=sp+"/"+d+"/direct_url.json";if(fs.existsSync(f)){const j=JSON.parse(fs.readFileSync(f));out=(j.vcs_info&&j.vcs_info.commit_id)||""}}}console.log(out)' "/opt/newsflows/tools/uv/$1" "$1"; }
assert_bindings_minimal() {  # what a RESTORE needs and nothing more: the approved packet, its literals, the tool refs, the rollback body
  local ph; ph=$(sha256sum "$PACKET_PATH" | cut -d' ' -f1); [[ "$ph" == "$EXPECTED_PACKET_SHA" ]] || die "packet $PACKET_PATH sha256 $ph != EXPECTED_PACKET_SHA $EXPECTED_PACKET_SHA"
  # every literal must appear in the approved packet OR in the owner's approval-B record (APPROVAL_B_PATH: the ledger text naming the
  # merged/predecessor commits and the request/rollback body hashes, which exist only after merge+projection+preview)
  local v; for v in "$EXPECTED_CLOCK" "$EXPECTED_FLOOR" "$EXPECTED_CONTRACT" "$EXPECTED_CATALOG_SHA" "$EXPECTED_PREDECESSOR_CATALOG_SHA"; do grep -qF -- "$v" "$PACKET_PATH" || die "value '$v' does not appear in the approved packet"; done
  # approval records are the OWNER'S verbatim words saved by the executing agent without paraphrase (header line
  # "OWNER APPROVAL (verbatim) -- Philipp -- <voice|chat|matrix> -- <UTC>"): B1 names the merged + predecessor commits (needed from
  # preview on), B2 names the request + rollback body hashes (needed from apply on). A pre-activation BASELINE (EXPECTED_CLOCK=receipt_time)
  # needs no approvals.
  # staged copies inside E (written by preview/apply) are the default, so a restore shell needs no operator environment for them
  APPROVAL_B1_PATH="${APPROVAL_B1_PATH:-$E/approval-B1.txt}"; APPROVAL_B2_PATH="${APPROVAL_B2_PATH:-$E/approval-B2.txt}"
  if [[ "$EXPECTED_CLOCK" != "receipt_time" && "${BINDINGS_MODE:-full}" != "restore" ]]; then
    approval_ok "$APPROVAL_B1_PATH" "$CATALOG_SOURCE_SHA" "$PREDECESSOR_SOURCE_SHA" || die "APPROVAL_B1_PATH ($APPROVAL_B1_PATH) missing, lacks the owner-attribution header, or lacks the two commit ids"
    if [[ -n "${EXPECTED_REQUEST_SHA:-}" || -n "${EXPECTED_ROLLBACK_SHA:-}" ]]; then approval_ok "$APPROVAL_B2_PATH" "${EXPECTED_REQUEST_SHA:-}" "${EXPECTED_ROLLBACK_SHA:-}" || die "APPROVAL_B2_PATH ($APPROVAL_B2_PATH) missing, lacks the owner-attribution header, or lacks the body hashes"; fi
  fi
  APPROVAL_A_PATH="${APPROVAL_A_PATH:-$E/approval-A.txt}"
  if [[ "$EXPECTED_CLOCK" != "receipt_time" && "${BINDINGS_MODE:-full}" != "restore" ]]; then approval_ok "$APPROVAL_A_PATH" "$EXPECTED_PACKET_SHA" "$EXPECTED_FLOOR" "D3(iv)" || die "APPROVAL_A_PATH ($APPROVAL_A_PATH) missing, lacks the owner-attribution header, or lacks the packet SHA / floor / amendment date"; fi
  APPROVAL_A_SHA=$( [[ -f "$APPROVAL_A_PATH" ]] && sha256sum "$APPROVAL_A_PATH" | cut -d' ' -f1 || echo absent ); APPROVAL_B1_SHA=$( [[ -f "$APPROVAL_B1_PATH" ]] && sha256sum "$APPROVAL_B1_PATH" | cut -d' ' -f1 || echo absent ); APPROVAL_B2_SHA=$( [[ -f "$APPROVAL_B2_PATH" ]] && sha256sum "$APPROVAL_B2_PATH" | cut -d' ' -f1 || echo absent )
  # export the bound values for callers that run this check in a subshell (battery): one line, parsed by bindings_capture
  echo "BINDINGS_OUT ${CATALOG_SHA:--} $APPROVAL_A_SHA $APPROVAL_B1_SHA $APPROVAL_B2_SHA $APPROVAL_A_PATH $APPROVAL_B1_PATH $APPROVAL_B2_PATH"
  local t exp got; for t in bsky-ops newsflows-bskyhealth blueskyranker; do exp=$(echo "$EXPECTED_TOOL_REFS" | tr ',' '\n' | awk -F= -v k="$t" '$1==k{print $2}'); grep -qF -- "$exp" "$PACKET_PATH" || die "tool ref $t=$exp not named in the approved packet"; got=$(tool_ref "$t"); [[ -n "$exp" && "$got" == "$exp" ]] || die "installed tool $t is '$got', expected '$exp'"; done
  local rk; for rk in $(echo "$EXPECTED_UPDATE_RKEYS" | tr ',' ' '); do grep -qF -- "$rk" "$PACKET_PATH" || die "rkey $rk not named in the approved packet"; done
  local d; d="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
  [[ "$(sha256sum "${BASH_SOURCE[0]}" | cut -d' ' -f1)" == "$EXPECTED_RUNNER_SHA" ]] || die "executing runner hash != EXPECTED_RUNNER_SHA"
  [[ "$(sha256sum "$d/scripts/served_content_shadow.sql" | cut -d' ' -f1)" == "$EXPECTED_SHADOW_SQL_SHA" ]] || die "served_content_shadow.sql hash != EXPECTED_SHADOW_SQL_SHA"
  [[ "$(sha256sum "$d/scripts/served_latency_from_logs.sh" | cut -d' ' -f1)" == "$EXPECTED_LATENCY_SH_SHA" ]] || die "served_latency_from_logs.sh hash != EXPECTED_LATENCY_SH_SHA"
  for v in "$EXPECTED_RUNNER_SHA" "$EXPECTED_SHADOW_SQL_SHA" "$EXPECTED_LATENCY_SH_SHA" "$EXPECTED_REQUESTER_SHA" "$EXPECTED_FEEDGEN_IMAGE" "$EXPECTED_SCORE_BACKED_FLOOR" "BSR_UNIT=$BSR_UNIT" "EXPECTED_BSR_HANDLES=$EXPECTED_BSR_HANDLES"; do grep -qF -- "$v" "$PACKET_PATH" || die "value '$v' does not appear in the approved packet"; done
  if [[ -f "$E/feedgen-bulk-rollback.json" ]]; then : "${EXPECTED_ROLLBACK_SHA:?EXPECTED_ROLLBACK_SHA is required once a rollback body exists}"; local rb; rb=$(sha256sum "$E/feedgen-bulk-rollback.json" | cut -d' ' -f1); [[ "$rb" == "$EXPECTED_ROLLBACK_SHA" ]] || die "rollback body hash $rb != EXPECTED_ROLLBACK_SHA $EXPECTED_ROLLBACK_SHA"; fi
}
assert_bindings() {  # full: minimal + catalog identity (deployed == origin@CATALOG_SOURCE_SHA == expected file hash), predecessor, readback TTL
  assert_bindings_minimal
  local d1 d2 d3; d1=$(sha256sum "$TREE_CATALOG" | cut -d' ' -f1); d2=$(sha256sum /opt/newsflows/config/newsflows/catalogs/publishers.yml | cut -d' ' -f1)
  d3=$(git -c safe.directory="$ROOT_CHECKOUT" -C "$ROOT_CHECKOUT" show "$CATALOG_SOURCE_SHA:config/newsflows/catalogs/publishers.yml" | sha256sum | cut -d' ' -f1)
  [[ "$d1" == "$d2" && "$d2" == "$d3" && "$d3" == "$EXPECTED_CATALOG_SHA" ]] || die "catalog identity: TREE_CATALOG $d1 / deployed $d2 / origin@$CATALOG_SOURCE_SHA $d3 / expected $EXPECTED_CATALOG_SHA differ"
  git -c safe.directory="$ROOT_CHECKOUT" -C "$ROOT_CHECKOUT" fetch -q origin || die "git fetch origin failed (this gate is not needed for a DB restore; use 'rollback' which asserts minimally)"
  git -c safe.directory="$ROOT_CHECKOUT" -C "$ROOT_CHECKOUT" merge-base --is-ancestor "$CATALOG_SOURCE_SHA" origin/main || die "CATALOG_SOURCE_SHA is not on origin/main"
  # predecessor: the first parent of the activation commit OR (content check) the commit whose publishers.yml equals the expected predecessor file hash
  local p1; p1=$(git -c safe.directory="$ROOT_CHECKOUT" -C "$ROOT_CHECKOUT" rev-parse "$CATALOG_SOURCE_SHA^1"); local pdh; pdh=$(git -c safe.directory="$ROOT_CHECKOUT" -C "$ROOT_CHECKOUT" show "$PREDECESSOR_SOURCE_SHA:config/newsflows/catalogs/publishers.yml" | sha256sum | cut -d' ' -f1)
  [[ "$PREDECESSOR_SOURCE_SHA" == "$p1" || "$pdh" == "$EXPECTED_PREDECESSOR_CATALOG_SHA" ]] || die "PREDECESSOR_SOURCE_SHA is neither the first parent of CATALOG_SOURCE_SHA nor carries the expected predecessor publishers.yml"
  [[ "$pdh" == "$EXPECTED_PREDECESSOR_CATALOG_SHA" ]] || die "predecessor publishers.yml sha $pdh != EXPECTED_PREDECESSOR_CATALOG_SHA"
  CATALOG_SHA=$d1
  echo "BINDINGS_OUT $CATALOG_SHA $APPROVAL_A_SHA $APPROVAL_B1_SHA $APPROVAL_B2_SHA $APPROVAL_A_PATH $APPROVAL_B1_PATH $APPROVAL_B2_PATH"
  # the BSR effective-config readback is a gate INPUT (bskyops compares its time_column to the constant createdAt, not to the catalog clock):
  # it must be fresh (documented 60-min TTL); the 5-min producer stalling would silently stale the sync/parity gates otherwise
  local rb_age; rb_age=$(node -e 'const j=JSON.parse(require("fs").readFileSync(process.argv[1]));const v=(j.artifact_metadata||{}).generated_at;const t=typeof v==="number"?v*1000:Date.parse(v);console.log(Math.round((Date.now()-t)/1000))' "$EFFECTIVE_CONFIG_JSON")
  [[ "$rb_age" =~ ^[0-9]+$ ]] && (( rb_age <= 3600 )) || die_precondition "BSR effective-config readback age ${rb_age}s exceeds the 60-min TTL (producer stalled?)"
}
predecessor_stage() {  # materialize the predecessor catalog dir from origin history -> echoes the dir
  local st=/opt/newsflows/deploy_staging/r4-predecessor-catalog-$PREDECESSOR_SOURCE_SHA; if [[ ! -f "$st/config/newsflows/catalogs/publishers.yml" ]]; then rm -rf "$st"; mkdir -p "$st"; git -c safe.directory="$ROOT_CHECKOUT" -C "$ROOT_CHECKOUT" archive "$PREDECESSOR_SOURCE_SHA" config/newsflows/catalogs | tar -x -C "$st"; fi; echo "$st/config/newsflows/catalogs"
}
parity_gate() {  # <json> <expected: matched|drift> [rkeys csv that must appear in the findings when drift]
  node -e 'const j=JSON.parse(require("fs").readFileSync(process.argv[1]));const exp=process.argv[2];const rk=(process.argv[3]||"").split(",").filter(Boolean);const sm=j.summary||{};const mc=sm.mismatch_count;if(typeof mc!=="number")throw new Error("summary.mismatch_count missing");if(exp==="matched"){if(!(j.status==="matched"&&mc===0))throw new Error("parity status="+j.status+" mismatch_count="+mc)}else{const f=JSON.stringify(j.findings||[]);const missing=rk.filter(r=>!f.includes(r));if(!(j.status==="drift"&&mc>0&&missing.length===0))throw new Error("negative control: status="+j.status+" mismatch_count="+mc+" rkeys_missing_in_findings="+missing)}console.log("parity "+j.status+" mismatch_count="+mc+" matched_feed_count="+sm.matched_feed_count+" finding_count="+sm.finding_count)' "$@"
}
tool_refs_line() { local d; d="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"; local ft; ft=$(git -c safe.directory="$d" -C "$d" rev-parse HEAD 2>/dev/null) || die "cannot resolve the executing feedgen tree commit"; echo "tool_refs bsky-ops=$(tool_ref bsky-ops) newsflows-bskyhealth=$(tool_ref newsflows-bskyhealth) blueskyranker=$(tool_ref blueskyranker) runner_sha256=$(sha256sum "${BASH_SOURCE[0]}" | cut -d' ' -f1) shadow_sql_sha256=$(sha256sum "$d/scripts/served_content_shadow.sql" | cut -d' ' -f1) latency_sh_sha256=$(sha256sum "$d/scripts/served_latency_from_logs.sh" | cut -d' ' -f1) feedgen_tree=$ft packet_sha256=$EXPECTED_PACKET_SHA catalog_sha256=${CATALOG_SHA:-} catalog_source_sha=$CATALOG_SOURCE_SHA predecessor_source_sha=$PREDECESSOR_SOURCE_SHA approval_a_sha256=${APPROVAL_A_SHA:-unset} approval_b1_sha256=${APPROVAL_B1_SHA:-unset} approval_b2_sha256=${APPROVAL_B2_SHA:-unset} approval_a_path=${APPROVAL_A_PATH:-unset} approval_b1_path=${APPROVAL_B1_PATH:-unset} approval_b2_path=${APPROVAL_B2_PATH:-unset} feedgen_image=$(docker inspect feedgen --format '{{.Image}}' 2>/dev/null || echo unknown)"; }
bindings_capture() {  # run assert_bindings in a subshell (so its die is classified by the caller) and import the bound values
  local out rc=0; out=$( assert_bindings 2>&1 ) || rc=$?; echo "$out" | grep -v '^BINDINGS_OUT ' >&2 || true
  local line; line=$(echo "$out" | sed -n 's/^BINDINGS_OUT //p' | tail -1); if [[ -n "$line" ]]; then read -r CATALOG_SHA APPROVAL_A_SHA APPROVAL_B1_SHA APPROVAL_B2_SHA APPROVAL_A_PATH APPROVAL_B1_PATH APPROVAL_B2_PATH <<<"$line"; fi; return $rc
}
escalate() {  # <reason> [catalog_reprojected] [parity]: P1 incident record + exit 3 (never the rollback code)
  local st; st=$(date -u +%H%M%S)
  { echo "ESCALATE at=$(ts) reason=$1"; echo "rows_restored=${ROWS_RESTORED:-unknown} catalog_reprojected=${2:-no} parity=${3:-unknown}"; echo "actions: freeze estate read-only; raw-free incident record = this dir; notify D8 on-call Philipp via ntfy:bsky-ranker-health within 15 min; NO third repair attempt"; tool_refs_line; } | emit "ESCALATE-$st.txt"; log "ESCALATE: $1"; exit 3
}
approval_ok() {  # <file> <literal...>: the owner's verbatim approval record must carry the attribution header and every literal
  local f=$1; shift; [[ -f "$f" ]] || return 1; grep -qE '^OWNER APPROVAL \(verbatim\) -- Philipp -- (voice|chat|matrix) -- 20[0-9]{2}-[0-9]{2}-[0-9]{2}T[0-9:]+Z' "$f" || return 1
  local body; body=$(grep -vE '^OWNER APPROVAL \(verbatim\) -- ' "$f"); [[ -n "$body" ]] || return 1   # literals must be in the OWNER'S words, not in the agent-written header
  local v; for v in "$@"; do [[ -z "$v" ]] && continue; if [[ "$v" == "0.80" ]]; then echo "$body" | grep -qE '0\.80?([^0-9]|$)' || return 1; else echo "$body" | grep -qF -- "$v" || return 1; fi; done; return 0
}
sync_packet() {  # -> $1 (json path); the sync packet is generated from the DEPLOYED catalog (identity-checked against origin/main)
  bskyops_env "$BSKYOPS" ecosystem desired-state feedgen-sync-packet --active-only --catalog-yaml "$TREE_CATALOG" --feedgen-url "$FEEDGEN_URL" --bsr-effective-config-json "$EFFECTIVE_CONFIG_JSON" --json > "$1"
}
dry_run_gate() { node -e 'const j=JSON.parse(require("fs").readFileSync(process.argv[1]));if(!(j.mode==="dry-run"&&j.status==="dry-run"&&(j.blockers||[]).length===0&&j.would_write===false))process.exit(2)' "$1"; }
gate_packet() {  # <packet.json>: exactly the expected rows x fields, symmetric rollback
  local f=$1
  node -e '
const j=JSON.parse(require("fs").readFileSync(process.argv[1]));const [rkeys,clock,floor,contract]=process.argv.slice(2);const exp=rkeys.split(",").sort();
const fail=(m)=>{console.error("gate: "+m);process.exit(2)};
if(j.status!=="ready-for-apply"||!(j.atomic_change_set&&j.atomic_change_set.atomic===true))fail("status "+j.status);
const b=j.atomic_change_set.request_body,rb=j.atomic_change_set.rollback_request_body;
const got=b.updates.map(u=>u.rkey).sort();if(JSON.stringify(got)!==JSON.stringify(exp))fail("rkeys "+got);
for(const u of b.updates){const k=Object.keys(u).filter(x=>!["op","rkey","if_current"].includes(x)).sort();
 if(JSON.stringify(k)!==JSON.stringify(["content_time_contract_version","content_time_cutover_min_valid_share","publisher_time_clock"]))fail(u.rkey+" fields "+k);
 if(u.publisher_time_clock!==clock||Number(u.content_time_cutover_min_valid_share)!==Number(floor)||u.content_time_contract_version!==contract)fail(u.rkey+" values");
 if(u.if_current.publisher_time_clock!=="receipt_time")fail(u.rkey+" if_current clock");}
if(!rb||rb.updates.length!==b.updates.length)fail("rollback size");
for(const u of rb.updates){if(u.publisher_time_clock!=="receipt_time"||u.if_current.publisher_time_clock!==clock)fail("rollback "+u.rkey)}
if((j.blockers||[]).length||(j.findings||[]).length)fail("blockers/findings");
console.log("gate ok updates="+b.updates.length);' "$f" "$EXPECTED_UPDATE_RKEYS" "$EXPECTED_CLOCK" "$EXPECTED_FLOOR" "$EXPECTED_CONTRACT"
}
cmd_preview() {
  if [[ "$EXPECTED_CLOCK" != "receipt_time" ]]; then install -d -o root -g newsflows -m 750 "$E"; [[ -n "${APPROVAL_A_PATH:-}" && ! -f "$E/approval-A.txt" ]] && install -o root -g newsflows -m 640 "$APPROVAL_A_PATH" "$E/approval-A.txt"; [[ -n "${APPROVAL_B1_PATH:-}" && ! -f "$E/approval-B1.txt" ]] && install -o root -g newsflows -m 640 "$APPROVAL_B1_PATH" "$E/approval-B1.txt"; fi
  [[ "$(docker inspect feedgen --format '{{.Image}}')" == "$EXPECTED_FEEDGEN_IMAGE" ]] || die "running feedgen image != EXPECTED_FEEDGEN_IMAGE"
  assert_bindings >/dev/null; load_keys; local p; p=$(mktemp); sync_packet "$p"; gate_packet "$p"
  emit feedgen-sync-packet-preview.json < "$p"; sha256sum "$E/feedgen-sync-packet-preview.json" | emit feedgen-sync-packet-preview.sha256
  node -e 'const j=JSON.parse(require("fs").readFileSync(process.argv[1]));console.log(JSON.stringify(j.atomic_change_set.request_body))' "$p" | emit feedgen-bulk-request.json
  node -e 'const j=JSON.parse(require("fs").readFileSync(process.argv[1]));console.log(JSON.stringify(j.atomic_change_set.rollback_request_body))' "$p" | emit feedgen-bulk-rollback.json
  # per-row dry-run against the running feedgen (read-only)
  local n=0; while IFS= read -r u; do local rk; rk=$(node -e 'console.log(JSON.parse(process.argv[1]).rkey)' "$u"); curl --fail -sS --max-time 30 -H "@$HDR" -H 'content-type: application/json' --data-binary "$u" "$FEEDGEN_URL/api/admin/feed_catalog/dry-run" | emit "dry-run-$rk.json"; dry_run_gate "$E/dry-run-$rk.json" || die "dry-run $rk not clean"; n=$((n+1)); done < <(node -e 'const j=JSON.parse(require("fs").readFileSync(process.argv[1]));for(const u of j.updates)console.log(JSON.stringify(u))' "$E/feedgen-bulk-request.json")
  { echo "generated_at=$(ts)"; echo "packet_path=$PACKET_PATH"; echo "packet_sha256=$EXPECTED_PACKET_SHA"; echo "catalog_sha256=$CATALOG_SHA (== deployed == origin@$CATALOG_SOURCE_SHA)"; echo "request_sha256=$(sha256sum "$E/feedgen-bulk-request.json" | cut -d' ' -f1)"; echo "rollback_sha256=$(sha256sum "$E/feedgen-bulk-rollback.json" | cut -d' ' -f1)"; echo "dry_runs=$n"; echo "feedgen_image=$(docker inspect feedgen --format '{{.Image}}')"; echo "expected=$EXPECTED_UPDATE_RKEYS clock=$EXPECTED_CLOCK floor=$EXPECTED_FLOOR contract=$EXPECTED_CONTRACT"; tool_refs_line; } | emit preview-summary.txt
  psqlq -c "SELECT rkey, catalog_revision, publisher_time_clock, content_time_cutover_min_valid_share, content_time_contract_version FROM feedgen_ops.feed_catalog WHERE enabled ORDER BY 1" | emit catalog-prestate.tsv
  # rollback artifacts recorded BEFORE the mutation: the predecessor catalog file (exact bytes) + its commit; and a NEGATIVE control of the
  # rollback dry-run gate: pre-apply the rollback body must be REFUSED by CAS (blockers non-empty) -- proves the gate discriminates
  local pd; pd=$(predecessor_stage); install -o root -g newsflows -m 640 "$pd/publishers.yml" "$E/catalog-predecessor.publishers.yml"; { echo "predecessor_source_sha=$PREDECESSOR_SOURCE_SHA"; echo "predecessor_publishers_sha256=$(sha256sum "$pd/publishers.yml" | cut -d' ' -f1)"; echo "activation_source_sha=$CATALOG_SOURCE_SHA"; echo "activation_publishers_sha256=$CATALOG_SHA"; } | emit rollback-artifacts.txt
  local nneg=0; while IFS= read -r u; do local rk; rk=$(node -e 'console.log(JSON.parse(process.argv[1]).rkey)' "$u"); curl -sS --max-time 30 -H "@$HDR" -H 'content-type: application/json' --data-binary "$u" "$FEEDGEN_URL/api/admin/feed_catalog/dry-run" | emit "rollback-dry-run-preapply-negative-$rk.json"; node -e 'const j=JSON.parse(require("fs").readFileSync(process.argv[1]));if(!(((j.blockers||[]).length>0)||(j.status&&j.status!=="dry-run")||j.error))process.exit(2)' "$E/rollback-dry-run-preapply-negative-$rk.json" || die "negative control: the rollback body was ACCEPTED pre-apply for $rk (CAS not enforced?)"; nneg=$((nneg+1)); done < <(node -e 'const j=JSON.parse(require("fs").readFileSync(process.argv[1]));for(const u of j.updates)console.log(JSON.stringify(u))' "$E/feedgen-bulk-rollback.json")
  echo "rollback_dry_run_negative_control_rows_refused=$nneg" | emit rollback-negative-control.txt
  # parity NEGATIVE control, pre-apply: the deployed activation catalog vs the live receipt-time rows must be reported as drift naming the four rkeys
  bskyops_env "$BSKYOPS" ecosystem desired-state feedgen-parity --active-only --catalog-yaml "$TREE_CATALOG" --feedgen-url "$FEEDGEN_URL" --bsr-effective-config-json "$EFFECTIVE_CONFIG_JSON" --json | emit feedgen-parity-preapply-negative-control.json || true
  parity_gate "$E/feedgen-parity-preapply-negative-control.json" drift "$EXPECTED_UPDATE_RKEYS" | emit feedgen-parity-preapply-negative-control-gate.txt || die "parity negative control (activation catalog vs live receipt rows) did not report drift on the four rkeys"
  rm -f "$p" "$HDR"; log "preview ok"
}
cmd_apply() {
  if [[ -n "${APPROVAL_B2_PATH:-}" && ! -f "$E/approval-B2.txt" ]]; then install -o root -g newsflows -m 640 "$APPROVAL_B2_PATH" "$E/approval-B2.txt"; fi
  assert_bindings >/dev/null; load_keys; [[ -f "$E/feedgen-bulk-request.json" && -f "$E/preview-summary.txt" ]] || die "run preview first"
  local t0; t0=$(ts)
  # the request body must be byte-identical to the previewed one and the live rows must still match if_current (fresh packet == same body)
  local p; p=$(mktemp); sync_packet "$p"; gate_packet "$p"
  local fresh; fresh=$(node -e 'const j=JSON.parse(require("fs").readFileSync(process.argv[1]));console.log(JSON.stringify(j.atomic_change_set.request_body))' "$p" | sha256sum | cut -d' ' -f1); local prev; prev=$(sha256sum "$E/feedgen-bulk-request.json" | cut -d' ' -f1)
  [[ "$fresh" == "$prev" ]] || die "live rows changed since preview (request body hash $fresh != $prev) -- re-preview and re-approve"
  : "${EXPECTED_REQUEST_SHA:?EXPECTED_REQUEST_SHA (the request-body SHA-256 the owner approved) is required for apply}"
  [[ "$prev" == "$EXPECTED_REQUEST_SHA" ]] || die "request body hash $prev != owner-approved EXPECTED_REQUEST_SHA $EXPECTED_REQUEST_SHA"
  : "${EXPECTED_ROLLBACK_SHA:?EXPECTED_ROLLBACK_SHA (the rollback-body SHA-256 the owner approved) is required for apply}"; [[ "$(sha256sum "$E/feedgen-bulk-rollback.json" | cut -d' ' -f1)" == "$EXPECTED_ROLLBACK_SHA" ]] || die "rollback body hash != owner-approved EXPECTED_ROLLBACK_SHA"
  local rid; rid=$prev; local resp; resp=$(mktemp); local http
  # x-feedgen-source == x-feedgen-request-id == request-body hash (feed_catalog_history.source records the source header); the packet
  # SHA rides in the actor header (free text) and in apply-transport.txt
  http=$(curl -sS --max-time 60 -H "@$HDR" -H "x-feedgen-actor: approved-activation-packet:$EXPECTED_PACKET_SHA" -H "x-feedgen-source: $rid" -H "x-feedgen-request-id: $rid" -H 'content-type: application/json' --data-binary "@$E/feedgen-bulk-request.json" --output "$resp" --write-out '%{http_code}' "$FEEDGEN_URL/api/admin/feed_catalog/bulk") || true
  emit feedgen-bulk-response.json < "$resp"; { echo "applied_at=$(ts)"; echo "http=$http"; echo "request_id=$rid"; echo "packet_sha256=$EXPECTED_PACKET_SHA"; tool_refs_line; } | emit apply-transport.txt
  [[ "$http" == "200" ]] || die "bulk apply http=$http (see feedgen-bulk-response.json); if ambiguous, run parity before deciding"
  node -e 'const j=JSON.parse(require("fs").readFileSync(process.argv[1]));const n=Number(process.argv[2]);if(!(j.status==="applied"&&j.applied===true&&j.result_count===n&&j.results.length===n))process.exit(2)' "$resp" "$(echo "$EXPECTED_UPDATE_RKEYS" | tr ',' '\n' | wc -l | tr -d ' ')" || die "bulk response not a clean apply"
  psqlq -c "SELECT rkey, catalog_revision, publisher_time_clock, content_time_cutover_min_valid_share, content_time_contract_version FROM feedgen_ops.feed_catalog WHERE enabled ORDER BY 1" | emit catalog-poststate.tsv
  # the intended cutover revisions (per rkey) -- every battery asserts served/catalog revisions against these
  awk -F'|' -v want=",$EXPECTED_UPDATE_RKEYS," 'index(want, ","$1",") {print $1"="$2}' "$E/catalog-poststate.tsv" | emit expected-catalog-revisions.txt
  [[ $(grep -c . "$E/expected-catalog-revisions.txt") -eq $(echo "$EXPECTED_UPDATE_RKEYS" | tr ',' '\n' | wc -l | tr -d ' ') ]] || die "expected-catalog-revisions.txt incomplete"
  local hist; hist=$(psqlq -c "SELECT rkey, revision, source, changed_at FROM feedgen_ops.feed_catalog_history WHERE rkey = ANY(string_to_array('$EXPECTED_UPDATE_RKEYS', ',')) AND source = '$rid' ORDER BY rkey"); echo "$hist" | emit catalog-history.tsv
  [[ $(echo "$hist" | grep -c "|$rid|") -eq $(echo "$EXPECTED_UPDATE_RKEYS" | tr ',' '\n' | wc -l | tr -d ' ') ]] || die "feed_catalog_history does not show one row per rkey with source=$rid"
  local nl; nl=$(docker logs feedgen --since "$t0" 2>&1 | grep -i "feed_catalog_changed\|catalog-listener: invalidated" | tail -40 || true); [[ -n "$nl" ]] || die "no feed_catalog_changed/catalog-listener lines in feedgen logs since $t0"; echo "$nl" | emit feedgen-log-notify.txt
  rm -f "$p" "$resp" "$HDR"; log "apply ok"
}
cmd_parity() {  # parity of the DEPLOYED catalog vs feedgen: status must be exactly "matched" with mismatch_count 0; plus a NEGATIVE control
  assert_bindings >/dev/null; local st; st=$(date -u +%H%M%S); local f="feedgen-parity-$st.json"
  bskyops_env "$BSKYOPS" ecosystem desired-state feedgen-parity --active-only --catalog-yaml "$TREE_CATALOG" --feedgen-url "$FEEDGEN_URL" --bsr-effective-config-json "$EFFECTIVE_CONFIG_JSON" --json | emit "$f"
  parity_gate "$E/$f" matched | emit "feedgen-parity-$st-gate.txt" || die "feedgen-parity not matched (see $f)"
  # negative control: the comparator must report the difference between the predecessor catalog file and the live rows (4 mismatches after apply)
  local pd; pd=$(predecessor_stage); local n=$(echo "$EXPECTED_UPDATE_RKEYS" | tr ',' '\n' | wc -l | tr -d ' ')
  bskyops_env "$BSKYOPS" ecosystem desired-state feedgen-parity --active-only --catalog-yaml "$pd/publishers.yml" --feedgen-url "$FEEDGEN_URL" --bsr-effective-config-json "$EFFECTIVE_CONFIG_JSON" --json | emit "feedgen-parity-negative-control-$st.json" || true
  if [[ "$EXPECTED_CLOCK" == "content_time_v1" ]]; then parity_gate "$E/feedgen-parity-negative-control-$st.json" drift "$EXPECTED_UPDATE_RKEYS" | emit "feedgen-parity-negative-control-$st-gate.txt" || die "parity negative control did not report drift on the four rkeys against the predecessor catalog"; fi
}
cmd_rollback_dryrun() {  # only meaningful AFTER apply (the rollback CAS expects the activated values); every row gated like the forward dry-run
  assert_bindings >/dev/null; load_keys; local n=0 stamp; stamp=$(date -u +%H%M%S); tool_refs_line | emit "rollback-dry-run-$stamp-bindings.txt"; while IFS= read -r u; do local rk; rk=$(node -e 'console.log(JSON.parse(process.argv[1]).rkey)' "$u"); curl --fail -sS --max-time 30 -H "@$HDR" -H 'content-type: application/json' --data-binary "$u" "$FEEDGEN_URL/api/admin/feed_catalog/dry-run" | emit "rollback-dry-run-$rk-$stamp.json"; dry_run_gate "$E/rollback-dry-run-$rk-$stamp.json" || die "rollback dry-run $rk not clean (see rollback-dry-run-$rk-$stamp.json)"; n=$((n+1)); done < <(node -e 'const j=JSON.parse(require("fs").readFileSync(process.argv[1]));for(const u of j.updates)console.log(JSON.stringify(u))' "$E/feedgen-bulk-rollback.json"); log "rollback dry-run ok ($n rows, all would_write=false, no blockers)"; }
cmd_rollback() { BINDINGS_MODE=restore assert_bindings_minimal >/dev/null; load_keys; local resp; resp=$(mktemp); local http; ROWS_RESTORED=no; http=$(curl -sS --max-time 60 -H "@$HDR" -H "x-feedgen-actor: approved-activation-packet-rollback" -H "x-feedgen-source: $EXPECTED_PACKET_SHA" -H "x-feedgen-request-id: rollback-$(sha256sum "$E/feedgen-bulk-rollback.json" | cut -c1-64)" -H 'content-type: application/json' --data-binary "@$E/feedgen-bulk-rollback.json" --output "$resp" --write-out '%{http_code}' "$FEEDGEN_URL/api/admin/feed_catalog/bulk") || true; emit "feedgen-bulk-rollback-response-$(date -u +%H%M%S).json" < "$resp"; echo "rolled_back_at=$(ts) http=$http" | emit "rollback-transport-$(date -u +%H%M%S).txt"; [[ "$http" == "200" ]] || escalate "rollback bulk POST http=$http (layer i failed; see the rollback response receipt)" no unknown
  node -e 'const j=JSON.parse(require("fs").readFileSync(process.argv[1]));const n=Number(process.argv[2]);if(!(j.status==="applied"&&j.applied===true&&j.result_count===n&&j.results.length===n))process.exit(2)' "$resp" "$(echo "$EXPECTED_UPDATE_RKEYS" | tr ',' '\n' | wc -l | tr -d ' ')" || escalate "rollback bulk response is not a clean apply of all rows (layer i)" no unknown
  local rs2; rs2=$(date -u +%H%M%S); psqlq -c "SELECT rkey, catalog_revision, publisher_time_clock, content_time_cutover_min_valid_share, content_time_contract_version FROM feedgen_ops.feed_catalog WHERE enabled ORDER BY 1" | emit "catalog-after-rollback-$rs2.tsv"
  node -e 'const rows=require("fs").readFileSync(process.argv[1],"utf8").split("\n").filter(l=>l.startsWith("newsflow-"));const want=process.argv[2].split(",");let bad=[];for(const w of want){const r=rows.find(l=>l.split("|")[0]===w);if(!r){bad.push(w+" missing");continue}const c=r.split("|");if(!(c[2]==="receipt_time"&&c[3]===""&&c[4]===""&&c[5]===""))bad.push(w+" state="+c.slice(2).join("|"))}console.log(bad.length?bad.join("; "):"rows restored: "+want.join(",")+" = receipt_time/null/null/null");if(bad.length)process.exit(2)' "$E/catalog-after-rollback-$rs2.tsv" "$EXPECTED_UPDATE_RKEYS" | emit "rollback-rowstate-gate-$rs2.txt" || escalate "post-restore row state is not receipt_time/null/null/null for all four rows (layer i)" no unknown
  ROWS_RESTORED=yes; { echo "rows_restored_at=$(ts)"; tool_refs_line; } | emit "rollback-transport-$rs2-bindings.txt"; rm -f "$resp" "$HDR"; log "rollback applied and verified (DB rows)"
  # (ii) re-project the PREDECESSOR catalog file so the deployed desired state matches the restored rows, then (iii) parity vs the predecessor.
  # Steps (ii)/(iii) never undo (i): a failure here is reported as "rows restored; catalog re-projection/parity pending" and is retried.
  set +e
  local pd; pd=$(predecessor_stage); local st; st=$(date -u +%H%M%S)
  escalate() { { echo "ESCALATE at=$(ts) reason=$1"; echo "rows_restored=yes catalog_reprojected=${2:-no} parity=${3:-unknown}"; echo "actions: freeze estate read-only; raw-free incident record = this dir; notify D8 on-call Philipp via ntfy:bsky-ranker-health within 15 min; NO third repair attempt"; tool_refs_line; } | emit "ESCALATE-$st.txt"; log "ESCALATE: $1"; exit 3; }
  local pdh; pdh=$(sha256sum "$pd/publishers.yml" | cut -d' ' -f1); [[ "$pdh" == "$EXPECTED_PREDECESSOR_CATALOG_SHA" ]] || escalate "predecessor file hash $pdh != expected; re-projection skipped" no unknown
  bskyops_env "$BSKYOPS" ecosystem catalog-sync-packet --source-root "$pd" --deployed-root /opt/newsflows/config/newsflows/catalogs --json | emit "rollback-catalog-sync-preview-$st.json"
  node -e 'const j=JSON.parse(require("fs").readFileSync(process.argv[1]));const acts=(j.actions||[]);const bad=acts.filter(a=>a.filename!=="publishers.yml"&&a.action!=="no-op");if(bad.length||!(j.status==="ready-for-apply"||j.status==="already-converged")){console.error("rollback re-projection would touch "+JSON.stringify(bad)+" status="+j.status);process.exit(2)}console.log("re-projection scope ok: "+acts.map(a=>a.filename+"="+a.action).join(","))' "$E/rollback-catalog-sync-preview-$st.json" | emit "rollback-catalog-sync-preview-$st-gate.txt" || escalate "re-projection preview out of scope -- NOT applied" no unknown
  bskyops_env "$BSKYOPS" ecosystem catalog-sync-apply --source-root "$pd" --deployed-root /opt/newsflows/config/newsflows/catalogs --confirm-live-host-catalog-sync --json | emit "rollback-catalog-sync-apply-$st.json"
  sha256sum /opt/newsflows/config/newsflows/catalogs/publishers.yml "$pd/publishers.yml" | emit "rollback-catalog-identity-$st.txt"
  bskyops_env "$BSKYOPS" ecosystem desired-state feedgen-parity --active-only --catalog-yaml /opt/newsflows/config/newsflows/catalogs/publishers.yml --feedgen-url "$FEEDGEN_URL" --bsr-effective-config-json "$EFFECTIVE_CONFIG_JSON" --json | emit "rollback-parity-$st.json"
  parity_gate "$E/rollback-parity-$st.json" matched | emit "rollback-parity-$st-gate.txt" || escalate "post-rollback parity not matched" yes DIFFERS
  set -e
  log "rollback complete: rows restored, predecessor catalog re-projected, parity matched. Merge the pre-opened revert PR so origin/main == deployed again."
}
cmd_battery() {  # <label>: per-invocation subdir; fresh authenticated requests first; every gate fails closed
  local L=${1:?label}
  if [[ "$EXPECTED_CLOCK" == "content_time_v1" ]]; then case "$L" in c1|c2) ;; *) die_precondition "battery label under content_time_v1 must be c1 or c2 (got '$L')";; esac; [[ -f "$E/apply-transport.txt" ]] || die_precondition "no apply-transport.txt in $E"; local at; at=$(sed -n 's/^applied_at=//p' "$E/apply-transport.txt" | head -1); [[ -z "${APPLIED_AT:-}" || "$APPLIED_AT" == "$at" ]] || die_precondition "APPLIED_AT '$APPLIED_AT' != apply-transport.txt applied_at '$at'"; APPLIED_AT=$at; else [[ "$L" == "baseline" ]] || die_precondition "a receipt_time battery must be labelled baseline"; : "${APPLIED_AT:?APPLIED_AT (ISO) is required for the baseline}"; fi
  bindings_capture || die_precondition "battery bindings/readback freshness not satisfied -- fix and re-run"
  [[ "$(docker inspect feedgen --format '{{.Image}}')" == "$EXPECTED_FEEDGEN_IMAGE" ]] || die "GATE FAIL: running feedgen image changed (!= EXPECTED_FEEDGEN_IMAGE)"
  local B="battery-$L-$(date -u +%Y%m%dT%H%M%SZ)"; install -d -o root -g newsflows -m 750 "$E/$B"; local E0=$E; E="$E/$B"
  { echo "label=$L"; echo "started_at=$(ts)"; echo "applied_at=$APPLIED_AT"; echo "bsr_unit=$BSR_UNIT"; echo "bsr_handles=$EXPECTED_BSR_HANDLES"; tool_refs_line; } | emit meta.txt
  # (0) fresh AUTHENTICATED served requests for every feed: run the canonical appview feed-health check now (it fetches each
  #     feed via the AppView relay as the health bot account -> new request_log rows, e2e latency in feed_health_latest.json)
  # wait for any in-flight standing run of the health fetch to finish, then start OUR run and prove it started after BSTART
  local w=0; while systemctl is-active --quiet bsr-feed-health.service && (( w < 180 )); do sleep 2; w=$((w+2)); done
  systemctl is-active --quiet bsr-feed-health.service && die_precondition "bsr-feed-health.service busy for 180 s before the battery -- re-run the battery"
  local BSTART; BSTART=$(ts); local inv0; inv0=$(systemctl show bsr-feed-health.service -p InvocationID --value); systemctl start bsr-feed-health.service; w=0; while systemctl is-active --quiet bsr-feed-health.service && (( w < 180 )); do sleep 2; w=$((w+2)); done
  systemctl is-active --quiet bsr-feed-health.service && die_precondition "bsr-feed-health.service still running after 180 s -- fresh authenticated requests not confirmed; re-run"
  local inv1 exst; inv1=$(systemctl show bsr-feed-health.service -p InvocationID --value); exst=$(systemctl show bsr-feed-health.service -p ExecMainStartTimestamp --value); [[ "$inv1" != "$inv0" ]] || die_precondition "bsr-feed-health.service did not run a NEW invocation for this battery; re-run"; echo "health_fetch_invocation=$inv1 started=$exst battery_start=$BSTART" | emit fresh-fetch-invocation.txt
  cp /opt/newsflows/blueskyranker_v2/logs/feed_health_latest.json /tmp/fh.$$ || die_precondition "feed_health_latest.json missing"; node -e 'const j=JSON.parse(require("fs").readFileSync(process.argv[1]));const want=process.argv[2].split(",");const fin=Date.parse(j.finished_at||j.started_at);if(!(fin>=Date.parse(process.argv[3])))throw new Error("feed_health_latest predates this battery start "+process.argv[3]);const arr=Array.isArray(j.feeds)?j.feeds:Object.entries(j.feeds).map(([k,v])=>({rkey:k,...v}));let bad=[];const seen=new Set();for(const f of arr){const rk=f.rkey||f.feed_id||f.k;if(!want.includes(rk))continue;const r=(f.results||[]).find(x=>x.name==="appview_authed_relay");const okk=r&&r.status==="OK";if(!okk)bad.push(rk);seen.add(rk);console.log(rk,f.overall,"authed_relay:",r&&r.status,"elapsed_sec:",r&&r.detail&&r.detail.elapsed_sec)}console.log("finished_at",j.finished_at);const missing=want.filter(w=>!seen.has(w));if(missing.length||bad.length){console.log("missing="+missing+" not_ok="+bad);process.exit(2)}' /tmp/fh.$$ "$EXPECTED_UPDATE_RKEYS" "$BSTART" | emit fresh-authenticated-requests.txt || { rm -f /tmp/fh.$$; die "GATE FAIL: fresh authenticated requests: a feed is missing or its authed relay fetch failed (see fresh-authenticated-requests.txt)"; }; rm -f /tmp/fh.$$
  # (1) BSR run evidence: journal lines of the main ranker after APPLIED_AT must show the expected clock/contract for all four handles
  # the FIRST COMPLETE main run after APPLIED_AT (from "Ranking clock resolved" to "Deactivated successfully"); lines of a run that
  # straddles APPLIED_AT are excluded; bsr-ranker@main serves exactly the four main feeds, so every line in the segment is theirs
  # the LAST complete run since PREV_RUN_AFTER (= the previous battery's analysed run start, or APPLIED_AT for the first battery); a run
  # that ended with a unit failure (or the divergent-contract literal) is a GATE FAIL; "no complete run yet" is bounded to two cadences
  # pointer semantics: prev_after = max(APPLIED_AT, pointer); the baseline never writes the pointer; the pointer advances only after ALL gates pass;
  # a post-apply battery other than the first requires the pointer (else precondition); the stall window is measured from prev_after
  local ptr=""; [[ -f "$E0/battery-last-run-start.txt" ]] && ptr=$(cat "$E0/battery-last-run-start.txt")
  if [[ "$EXPECTED_CLOCK" == "content_time_v1" && "$L" != "c1" && -z "$ptr" ]]; then die_precondition "battery $L: battery-last-run-start.txt is missing (was cycle 1 run in this E?)"; fi
  local prev_after; prev_after=$(printf '%s\n%s\n' "$APPLIED_AT" "${ptr:-$APPLIED_AT}" | sort | tail -1)
  local since_epoch; since_epoch=$(date -u -d "$prev_after" +%s) || die_precondition "cannot parse prev_after=$prev_after"
  local jraw jrc=0; jraw=$(journalctl -u "$BSR_UNIT" --since "@$since_epoch" --no-pager 2>&1) || jrc=$?
  (( jrc == 0 )) || die_precondition "journalctl failed (rc=$jrc): $(echo "$jraw" | head -2)"
  [[ -n "$jraw" && "$jraw" != *"-- No entries --"* ]] || die_precondition "journal has no $BSR_UNIT entries since $prev_after (unit name / journal access?)"
  local jl; jl=$(echo "$jraw" | grep -i "Ranking clock resolved\|Deactivated successfully\|Failed with result\|Main process exited\|_query_posts called\|ENGAGEMENT_EXPORT_TRANSITIONAL\|Shared feeds have divergent effective time contracts\|Finished handle" || true); echo "$jl" | emit bsr-main-journal.txt
  echo "$jl" | grep -q "Shared feeds have divergent effective time contracts" && die "GATE FAIL: BSR reported 'Shared feeds have divergent effective time contracts' since $prev_after (mixed-clock group) -- rollback"
  local cad; cad=$(node -e 'const j=JSON.parse(require("fs").readFileSync(process.argv[1]));let c=0;for(const b of Object.values(j.bindings||{})){const want=process.argv[2].split(",");if((b.feed_ids||[]).some(f=>want.includes(f)))c=Math.max(c,b.cadence_minutes||0)}console.log(c||30)' "$EFFECTIVE_CONFIG_JSON" "$EXPECTED_UPDATE_RKEYS")
  local seg; seg=$(node -e 'const t=require("fs").readFileSync(process.argv[1],"utf8").split("\n").filter(Boolean);const after=Date.parse(process.argv[2]);const cad=Number(process.argv[3]);let runs=[];let cur=null;let straddle=[];for(const l of t){if(/Ranking clock resolved/.test(l)){const m=l.match(/ranking_as_of=(\S+)/);cur={start:m?m[1]:l,lines:[l],end:null};runs.push(cur);continue}if(!cur){if(/Failed with result|Main process exited/.test(l))straddle.push(l);continue}cur.lines.push(l);if(/Deactivated successfully/.test(l)){cur.end="ok";cur=null}else if(/Failed with result|Main process exited/.test(l)){cur.end="failed";cur=null}}const norm=(x)=>x.replace(/\.(\d{3})\d*/,".$1").replace(/\+00:00$/,"Z");const failed=runs.filter(r=>r.end==="failed");if(failed.length){console.log("RUN_FAILED="+failed.map(r=>r.start).join(";"));process.exit(0)}if(straddle.length)console.error("STRADDLE_FAILED_IGNORED="+straddle.length+" (unit failure lines before the first clock resolution in the window belong to a run that started before it -- excluded per the straddling-run rule)");const complete=runs.filter(r=>r.end==="ok"&&Date.parse(norm(r.start))>after);if(!runs.length)console.log("NO_RUN_STARTED");else if(!complete.length)console.log("RUN_IN_PROGRESS");else{const first=complete[0];const gap=(Date.parse(norm(first.start))-after)/60000;console.log("RUN_START="+first.start+" RUN_END=ok GAP_MIN="+gap.toFixed(1)+" CADENCE_MIN="+cad+" COMPLETE_RUNS="+complete.length+(gap>1.5*cad?" NOT_ADJACENT":" adjacent")+" LAST_RUN_START="+complete[complete.length-1].start);for(const r of complete){console.log("--- run "+r.start);console.log(r.lines.join("\n"))}}' "$E/bsr-main-journal.txt" "$prev_after" "$cad")
  local age_min; age_min=$(( ( $(date -u +%s) - since_epoch ) / 60 ))
  [[ "$seg" == RUN_FAILED* ]] && die "GATE FAIL: a BSR main run since $prev_after ended in a unit failure ($seg) -- no fresh scores; rollback"
  if [[ "$seg" == "NO_RUN_STARTED" || "$seg" == "RUN_IN_PROGRESS" ]]; then (( age_min > 2*cad )) && die "GATE FAIL: no complete BSR main run for ${age_min} min since the last analysed run (> two ${cad}-min cadences) -- ranking is stalled; rollback"; die_precondition "BSR main: $seg since $prev_after -- wait for the cycle to finish, then re-run battery (becomes a gate FAIL after $((2*cad)) min without a completed run)"; fi
  echo "$seg" | emit bsr-main-run-segment.txt
  local hdr; hdr=$(echo "$seg" | head -1); local run_start; run_start=$(echo "$hdr" | sed -n 's/^RUN_START=\(\S*\) RUN_END=.*/\1/p')
  echo "$hdr" | grep -q "NOT_ADJACENT" && die "GATE FAIL: the first complete run after $prev_after ($run_start) is not the adjacent cycle (gap > 1.5 cadences); consecutive cycles not evidenced"
  echo "analysed_run_start=$run_start previous_after=$prev_after $hdr" | emit bsr-main-run-identity.txt
  node -e 'const all=require("fs").readFileSync(process.argv[1],"utf8");const clock=process.argv[2];const want=clock==="content_time_v1"?/time_column=content_time_v1/:/time_column=createdAt/;const handles=process.argv[3].split(",");const blocks=all.split(/^--- run /m).slice(1);let anyBad=false;for(const b of blocks){const t=b;const q=(t.match(/_query_posts called[^\n]*/g)||[]);const ex=(t.match(/ENGAGEMENT_EXPORT_TRANSITIONAL[^\n]*/g)||[]);const bad=q.filter(l=>!want.test(l));const seenH=handles.filter(h=>q.some(l=>l.includes(h)));let exBad=[];if(clock==="content_time_v1")exBad=ex.filter(l=>!/time_clock=\x27content_time_v1\x27 contract_version=\x27newsflows-content-time\/v2\x27/.test(l));const ok=seenH.length===handles.length&&bad.length===0&&(clock!=="content_time_v1"||ex.length===0);console.log("run "+t.split("\n")[0]+" handles_seen="+seenH.length+"/"+handles.length+" query_posts_lines="+q.length+" wrong_clock="+bad.length+" transitional_export_lines="+ex.length+" (must be 0 under content_time_v1: BSR logs the TRANSITIONAL warning only on the receipt_time path; positive science-path evidence is checked separately) export_wrong_clock="+exBad.length+(ok?" ok":" BAD"));if(!ok)anyBad=true;}console.log("runs_examined="+blocks.length);if(!blocks.length||anyBad)process.exit(2);' "$E/bsr-main-run-segment.txt" "$EXPECTED_CLOCK" "$EXPECTED_BSR_HANDLES" | emit bsr-main-gate.txt || die "GATE FAIL: BSR run evidence not on the expected clock for all four handles in EVERY complete run since $prev_after (see bsr-main-run-segment.txt) -- rollback"
  node "$(dirname "${BASH_SOURCE[0]}")/engagement_export_contract_gate.js" "$E/bsr-main-run-segment.txt" "$EXPECTED_UPDATE_RKEYS" "$EXPECTED_CLOCK" "$EXPECTED_CONTRACT" | emit bsr-engagement-export-contract-gate.txt || die "GATE FAIL: missing or ambiguous positive engagement-export contract evidence (see bsr-main-run-segment.txt) -- rollback"
  # (2) served content-shadow (oracle = deployed ranker-priority ordering: coalesce(score,-1) desc, content_time_utc desc, indexedAt desc, uri desc)
  psqlq -q -v rkeys="$EXPECTED_UPDATE_RKEYS" -v requester_sha="$EXPECTED_REQUESTER_SHA" -v bstart="$BSTART" -f - < "$(dirname "$0")/served_content_shadow.sql" | emit served-shadow.tsv
  set +e
  node -e 'const rows=require("fs").readFileSync(process.argv[1],"utf8").split("\n").filter(l=>l.startsWith("newsflow-"));const [clock,applied]=process.argv.slice(2);let bad=[];let pre=[];const revFile=process.argv[6];const expRev={};if(revFile&&require("fs").existsSync(revFile))for(const l of require("fs").readFileSync(revFile,"utf8").split("\n").filter(Boolean)){const [k,v]=l.split("=");expRev[k]=v}for(const l of rows){const c=l.split("\t");const [rk,catClock,catRev,sClock,sRev,servedAt,n,notValid,outside,inv,scored,sha,unjoined,future,reqId,reqSha]=c;if(catClock!==clock)bad.push(rk+" catalog_clock="+catClock);if(sClock!==clock)bad.push(rk+" served_clock="+sClock);if(sRev!==catRev)bad.push(rk+" served_revision "+sRev+"!="+catRev);if(clock==="content_time_v1"){if(!expRev[rk])bad.push(rk+" no expected revision recorded at apply");else if(String(catRev)!==String(expRev[rk])||String(sRev)!==String(expRev[rk]))bad.push(rk+" revision "+catRev+"/"+sRev+" != intended cutover revision "+expRev[rk]);}if(!servedAt||servedAt==="")pre.push(rk+" no request by the expected requester since "+applied);else if(!(Date.parse(servedAt)>=Date.parse(applied)))pre.push(rk+" served_at "+servedAt+" precedes the battery fresh fetch "+applied);if(reqSha!==process.argv[5])pre.push(rk+" requester_sha256 "+reqSha+" != expected (SQL selects by requester; empty = no fresh row)");console.log(rk+" analysed_request_id="+reqId+" requester_sha256="+reqSha+" served_at="+servedAt);if(Number(n)===0)bad.push(rk+" no served publisher rows");if(clock==="content_time_v1"&&(Number(notValid)||Number(outside)||Number(future)))bad.push(rk+" not_valid="+notValid+" outside="+outside+" future="+future);if(Number(inv))bad.push(rk+" inversions="+inv);if(Number(scored)===0)bad.push(rk+" served_scored=0");if(Number(unjoined))bad.push(rk+" unjoined_request_posts="+unjoined);}const wantN=process.argv[4].split(",").length;if(rows.length!==wantN)bad.push("expected "+wantN+" feed rows, got "+rows.length);if(pre.length){console.log("PRECONDITION: "+pre.join("; "));process.exit(3)}console.log(bad.length?bad.join("\n"):"served-shadow ok rows="+rows.length);if(bad.length)process.exit(2)' "$E/served-shadow.tsv" "$EXPECTED_CLOCK" "$BSTART" "$EXPECTED_UPDATE_RKEYS" "$EXPECTED_REQUESTER_SHA" "$E0/expected-catalog-revisions.txt" > /tmp/ssg.$$ ; local src=$?; set -e; emit served-shadow-gate.txt < /tmp/ssg.$$; rm -f /tmp/ssg.$$; (( src == 3 )) && die_precondition "served shadow: no request by the health bot after this battery's fetch start (timer race / fetch did not land) -- re-run the battery"; (( src == 0 )) || die "GATE FAIL: served shadow (see served-shadow-gate.txt) -- rollback"
  # (3) served-assumptions per feed (0.80 score-backed @24h, time_contract, revision), fail closed on invocation failure
  local rk; for rk in $(echo "$EXPECTED_UPDATE_RKEYS" | tr ',' ' '); do local did; did=$(psqlq -t -c "SELECT publisher_did FROM feedgen_ops.feed_catalog WHERE rkey='$rk'"); "$HEALTH_PY" -m bskyhealth.checks.feed_served_assumptions --rkey "$rk" --publisher-did "$did" --algo-policy-id ranker-priority --window-hours 3 --json-out "/tmp/sa.$$.json" --quiet < /dev/null || die "served-assumptions invocation failed for $rk"; emit "served-assumptions-$rk.json" < "/tmp/sa.$$.json"; rm -f "/tmp/sa.$$.json"; node -e 'const j=JSON.parse(require("fs").readFileSync(process.argv[1]));const f=j.feeds[0];const rc=(f.results||[]).find(r=>r.name==="ranker_serving_contract")||{};const tc=(f.results||[]).find(r=>r.name==="time_contract")||{};const d=rc.detail||{};console.log(process.argv[2],"overall="+j.overall,"latest_rev="+(f.latest_request||{}).catalog_revision,"rsc="+rc.status,"share="+d.observed_score_backed_share,"floor="+d.minimum_score_backed_share,"max_age_h="+d.ranker_score_max_age_hours,"time_contract="+tc.status);const sf=Number(process.argv[3]);if(!(j.overall==="OK"&&rc.status==="OK"&&Math.abs(Number(d.minimum_score_backed_share)-sf)<1e-9&&Number(d.ranker_score_max_age_hours)===24&&Number(d.observed_score_backed_share)+1e-9>=sf))process.exit(2)' "$E/served-assumptions-$rk.json" "$rk" "$EXPECTED_SCORE_BACKED_FLOOR" | emit "served-assumptions-$rk-gate.txt" || die "served-assumptions gate failed for $rk"; done
  # (4) D5 latency: served-log pairs since APPLIED_AT (p95/max are the gate; the >=30-sample count is reported, not gated -- it accrues)
  DOCKER="docker" bash "$(dirname "$0")/served_latency_from_logs.sh" "$APPLIED_AT" "$EXPECTED_UPDATE_RKEYS" 5000 8000 1 | emit latency.json
  node -e 'const j=JSON.parse(require("fs").readFileSync(process.argv[1]));let bad=[];for(const [k,v] of Object.entries(j.feeds)){if(v.samples===0)bad.push(k+" no samples yet");else if(!(v.p95_ms<=5000&&v.max_ms<=8000))bad.push(k+" p95="+v.p95_ms+" max="+v.max_ms);console.log(k,"samples="+v.samples,"p95="+v.p95_ms,"max="+v.max_ms)}if(bad.length){console.log(bad.join("\n"));process.exit(2)}' "$E/latency.json" | emit latency-gate.txt || die "latency gate failed (see latency-gate.txt)"
  # (5) readiness composite: the four feeds, time_contract component, floor, revision; artifact must be fresh
  cp /var/lib/newsflows/health-checker/feed_readiness_latest.json /tmp/fr.$$ || die_precondition "readiness artifact missing"
  local rage; rage=$(node -e 'const j=JSON.parse(require("fs").readFileSync(process.argv[1]));console.log(Math.round((Date.now()-Date.parse(j.generated_at))/1000))' /tmp/fr.$$); (( rage <= 2400 )) || { rm -f /tmp/fr.$$; die_precondition "readiness artifact is ${rage}s old (health timer not ticked since the apply?) -- wait for the tick and re-run"; }
  local basef=""; basef=$(ls -1 "$E0"/battery-baseline-*/readiness-components.json 2>/dev/null | tail -1 || true)
  if [[ "$EXPECTED_CLOCK" == "content_time_v1" && -z "$basef" ]]; then rm -f /tmp/fr.$$; die_precondition "no baseline readiness-components.json in $E0 -- run 'battery baseline' in THIS execution root before apply"; fi
  # readiness gate = the components content time can affect: time_contract must be OK; no other component may REGRESS versus the
  # pre-activation baseline battery (a lane that was already failing before the apply -- e.g. NER coverage -- is recorded, not a
  # rollback trigger); the artifact must be fresh
  set +e
  node -e 'const j=JSON.parse(require("fs").readFileSync(process.argv[1]));const want=process.argv[2].split(",");const clock=process.argv[3];const basePath=process.argv[4];const base=basePath?JSON.parse(require("fs").readFileSync(basePath)):null;const age=(Date.now()-Date.parse(j.generated_at))/1000;let bad=[],notes=[];const snap={};for(const f of j.feeds){const id=f.catalog&&f.catalog.feed_id;if(!want.includes(id))continue;const comps=f.components||{};snap[id]={};for(const [k,c] of Object.entries(comps))snap[id][k]=c.status;const tc=comps.time_contract||{};const st=f.overall||f.status;console.log(id,st,"time_contract:",tc.status,(tc.summary||"").slice(0,100),"clock:",f.catalog.publisher_time_clock,"valid_share:",f.catalog.content_time_valid_share,"floor:",f.catalog.content_time_cutover_min_valid_share,"rev:",f.catalog.catalog_revision);if(tc.status!=="OK")bad.push(id+" time_contract="+tc.status);if(f.catalog.publisher_time_clock!==clock)bad.push(id+" clock="+f.catalog.publisher_time_clock);if(clock==="content_time_v1"&&Math.abs(Number(f.catalog.content_time_cutover_min_valid_share)-Number(process.argv[5]))>1e-9)bad.push(id+" floor="+f.catalog.content_time_cutover_min_valid_share+" != expected "+process.argv[5]);const nc=comps.ner_coverage||{};console.log(id,"ner_coverage:",nc.status,(nc.summary||"").slice(0,120));for(const [k,c] of Object.entries(comps)){if(k==="time_contract")continue;if(k==="ner_coverage"||k==="embedding_coverage"){if(c.status!=="OK"&&c.status!=="SKIP")notes.push(id+" "+k+"="+c.status+" (preprocessing-coverage lane: windows on createdAt/indexedAt, clock-independent -- recorded, not gated)");continue}const b=base&&base[id]&&base[id][k];const rank=(x)=>x==="OK"?0:x==="SKIP"?0:x==="WARN"?1:x==="FAIL"?2:1;if(!base){if(c.status!=="OK"&&c.status!=="SKIP")notes.push(id+" "+k+"="+c.status+" (baseline run: recorded, not gated)");}else if(c.status==="FAIL"&&(b===undefined||rank(c.status)>rank(b)))bad.push(id+" "+k+" regressed to FAIL (baseline "+(b||"n/a")+")");else if(c.status!=="OK"&&c.status!=="SKIP")notes.push(id+" "+k+"="+c.status+" (baseline "+(b||"n/a")+", pre-existing)");}}require("fs").writeFileSync("/tmp/rc."+process.pid+".json",JSON.stringify(snap));console.log("snapshot=/tmp/rc."+process.pid+".json");console.log("generated_at",j.generated_at,"age_s",Math.round(age));if(notes.length)console.log("pre-existing non-OK (not gated): "+notes.join("; "));if(bad.length){console.log("GATE: "+bad.join("; "));process.exit(2)}' /tmp/fr.$$ "$EXPECTED_UPDATE_RKEYS" "$EXPECTED_CLOCK" "$basef" "$EXPECTED_FLOOR" > /tmp/rg.$$ ; local rrc=$?; set -e
  emit readiness-gate.txt < /tmp/rg.$$; local snapf; snapf=$(sed -n 's/^snapshot=//p' /tmp/rg.$$); [[ -n "$snapf" && -f "$snapf" ]] && { emit readiness-components.json < "$snapf"; rm -f "$snapf"; }; rm -f /tmp/rg.$$ /tmp/fr.$$
  (( rrc == 0 )) || die "GATE FAIL: readiness (time_contract not OK, wrong clock, or a component regressed to FAIL vs the baseline -- see readiness-gate.txt); if the composite merely predates the apply, wait for the health tick and re-run"
  # (6) rollback dry-run (D3(v)) INTO THIS BATTERY DIR: after apply the restore body must be valid against the activated rows (mandatory)
  if [[ "$EXPECTED_CLOCK" == "content_time_v1" ]]; then [[ -f "$E0/feedgen-bulk-rollback.json" && -f "$E0/apply-transport.txt" ]] || die "battery under content_time_v1 requires the apply artifacts in $E0"; load_keys; local n=0; while IFS= read -r u; do local rk2; rk2=$(node -e 'console.log(JSON.parse(process.argv[1]).rkey)' "$u"); curl --fail -sS --max-time 30 -H "@$HDR" -H 'content-type: application/json' --data-binary "$u" "$FEEDGEN_URL/api/admin/feed_catalog/dry-run" | emit "rollback-dry-run-$rk2.json"; dry_run_gate "$E/rollback-dry-run-$rk2.json" || die "rollback dry-run $rk2 not clean"; n=$((n+1)); done < <(node -e 'const j=JSON.parse(require("fs").readFileSync(process.argv[1]));for(const u of j.updates)console.log(JSON.stringify(u))' "$E0/feedgen-bulk-rollback.json"); echo "rollback_dry_run_rows_ok=$n" | emit rollback-dry-run-gate.txt; rm -f "$HDR"; HDR=""; fi
  # (7) conformance summary (sudo scan) -- fail closed if the scan itself fails
  local cs rc=0; cs=$( ( set -a; . "$ENV_FILE"; set +a; "$BSKYOPS" ecosystem conformance scan --json 2>/dev/null ) ) || rc=$?   # canonical invocation (runbook): root + feedgen env sourced, else the L1 readbacks report "blocked"   # rc=1 means "drift" (a verdict, not a failure); no JSON = failure
  echo "$cs" | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{const j=JSON.parse(s);const base=new Set(process.argv[2].split(",").filter(Boolean));const items=j.checks||j.items||j.results||[];const arr=Array.isArray(items)?items:Object.entries(items).map(([k,v])=>({name:k,...v}));const nonok=arr.filter(x=>x&&x.status&&x.status!=="ok").map(x=>(x.name||x.check)+"="+x.status);const newDrift=nonok.filter(n=>!base.has(n.split("=")[0]));if(!arr.length){const dc=(j.summary||{}).drift_count||0;if(dc>base.size)newDrift.push("drift_count="+dc+">"+base.size)}console.log("summary="+JSON.stringify(j.summary)+" scan_rc="+process.argv[1]+" non_ok="+nonok.join(",")+" baseline="+[...base].join(",")+" new_non_ok="+newDrift.join(","));if(newDrift.length||((j.summary||{}).blocked_count||0)>0)process.exit(2)})' "$rc" "$CONFORMANCE_BASELINE_DRIFT" | emit conformance.txt || die "conformance: new drift or blocked items beyond the recorded baseline (see conformance.txt)"
  local last_start; last_start=$(echo "$hdr" | sed -n 's/.*LAST_RUN_START=\(\S*\).*/\1/p'); [[ -n "$last_start" ]] || last_start=$run_start
  if [[ "$EXPECTED_CLOCK" == "content_time_v1" ]]; then echo "$last_start" | sed -E 's/\.([0-9]{3})[0-9]*/.\1/; s/\+00:00$/Z/' > /tmp/lrs.$$; install -o root -g newsflows -m 640 /tmp/lrs.$$ "$E0/battery-last-run-start.txt.$L"; cp -f "$E0/battery-last-run-start.txt.$L" "$E0/battery-last-run-start.txt"; rm -f /tmp/lrs.$$; fi
  E=$E0; log "battery $L complete: all gates passed (receipts in $B)"
}
case "${1:-}" in preview) cmd_preview;; apply) cmd_apply;; parity) cmd_parity;; rollback-dryrun) cmd_rollback_dryrun;; rollback) cmd_rollback;; battery) cmd_battery "${2:?label}";; *) echo "usage: $0 preview|apply|parity|rollback-dryrun|rollback|battery <label>" >&2; exit 2;; esac
